In [2]:
import numpy as np

In [4]:
def construir_matrices(dimension, tamaño):
    M_secreto = np.random.randint(0, 2, size=tamaño)
    M_secreto = M_secreto.reshape(dimension, dimension)
    M_muestra = np.zeros([dimension, dimension], dtype=str)
    M_muestra[:] = '-'
    return (M_secreto, M_muestra)

In [6]:
def descubrir_celdas(fila, columna, perdio, puntaje):
    if M_secreto[fila, columna] == 0:
        M_muestra[fila, columna] = 'o'
        puntaje += 1
        print('¡NINGUNA MINA POR AQUÍ! Puntaje: ', puntaje)
        print()
        print(M_muestra)
        return (perdio, puntaje)
    else:
        print('¡UNA GRAN EXPLOSIÓN OCURRIÓ EN EL TABLERO!')
        print()
        print('Puntaje final: ', puntaje)
        print()
        print(M_secreto)
        perdio = True
        return (perdio, puntaje)

In [28]:
# Seteo variables iniciales
nombre = input('Nombre: ')
print('¡Hola ' + nombre +'!')
opciones = {'1':4, '2':8, '3':12}
print()
print('Por favor, elegí la dimensión del tablero')
print('1) 4x4')
print('2) 8x8')
print('3) 12x12')
opcion = input('Opción: ')
dimension = opciones[opcion]
tamaño = dimension ** 2
print()
M_secreto, M_muestra = construir_matrices(dimension, tamaño)
cant_ceros = len(np.where(M_secreto == 0)[0])
print('Comienza el juego...')
print()
print(M_muestra)
perdio = False
puntaje = 0
contador = 0

while not perdio:
    fila = int(input('Ingresá la fila de la celda que querés descubrir: '))
    columna = int(input('Ahora la columna: '))
    print()
    perdio, puntaje = descubrir_celdas(fila, columna, perdio, puntaje)
    contador += 1
    if contador == cant_ceros:
        print('¡GANASTE ' + nombre + ' !')
        perdio = True

Nombre: Bibo
¡Hola Bibo!

Por favor, elegí la dimensión del tablero
1) 4x4
2) 8x8
3) 12x12
Opción: 2

Comienza el juego...

[['-' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '-']]
Ingresá la fila de la celda que querés descubrir: 0
Ahora la columna: 0

¡NINGUNA MINA POR AQUÍ! Puntaje:  1

[['o' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '-']]
Ingresá la fila de la celda que querés descubrir: 1
Ahora la columna: 1

¡UNA GRAN EXPLOSIÓN OCURRIÓ EN EL TABLERO!

Puntaje final:  1

[[0 0 0 1 1 1 1 0]
 [1 1 0 0 1 0 0 1]
 [1 1 0 0 0 1 0 0]
 [1 0 0 1 0